### ISSUE TITLE
File is not saved in Android

### ISSUE THREAD

**Issue by torayeff** [emj365/cordova-plugin-audio-recorder-api#15]
I have run this in Android 4.4.2. It records, it plays back  and it shows file location but the file is not saved there. Maybe it gets deleted somehow.
/data/data/app-id/files/file-id.m4a

**Comment by emj365** [comment]
Make sure there are `app-id` and `file-id`: /data/data/<app-id>/files/<file-id>.m4a

If you can not see it with something like file bowser app. Please connect your phone to your PC and try `adb shell` (you will need Android SDK):

```
$ adb shell
$ su
$ ls /data/data/
<find your app folder>
$ ls /data/data/com.ionicframework.testionic223576/files # for example
34ccd93a-4e04-42de-a00d-59cc90cf1654.m4a
5367cb6c-2741-4a75-bb5e-62ce2fe9f068.m4a
93f713d4-723f-4989-9dab-d8ff9aef3780.m4a
99c62da8-351a-49be-a60c-7ce887a50bda.m4a
9ef6e19c-01b4-451d-8239-ef1303596699.m4a
```

**Comment by torayeff** [comment]
Can you please explain why I can not see it with phone's default file browser? I tried enabling "Show hidden files", but  it is still not visible.

**Comment by emj365** [comment]
Can't tell very detail. But the phone file browser must have not right permission to do that.
