### ISSUE TITLE
invalid action ?

### ISSUE THREAD

**Issue by 519818538** [emj365/cordova-plugin-audio-recorder-api#23]
I   clicked  the record,but it alert invalid action in android.Why?

**Comment by 519818538** [comment]
I used  the plugin like this:

```
 $scope.record=function(){
                window.plugins.audioRecorderAPI.record(function(msg) {
                    // complete
                    alert('ok: ' + msg);
                }, function(msg) {
                    // failed
                    alert('ko: ' + msg);
                }, 30); // record 30 seconds



            };
```

**Comment by emj365** [comment]
Please check if plugin installed.

**Comment by Alexorz** [comment]
Hi there, I got a same issue in my ionic project, audio works fine at the first time calling `record()`, but always alert 'invalid action' at the next callings.

env:
- Android v5.1.1
- ionic v1.7.14
- cordova v6.1.1
- cordova-plugin-audio-recorder-api v0.0.6

**Comment by amirhere** [comment]
I've got the same issue reported by Alexorz in the previous message
