### ISSUE TITLE
volume settings

### ISSUE THREAD

**Issue by e-oz** [emj365/cordova-plugin-audio-recorder-api#8]
thank you for this plugin, it's the only one I managed to work with Ionic :)

is there any way to setup volume of recording/playback?

**Comment by emj365** [comment]
You're welcome. I'm happy to hear people use the plugin that I build.
So far, It can't control the volume. :(

But I think it can implement both recording and playback. 
I made this plugin for a demo of a project, so I will improve the plugin when the project starts.

**Comment by kerlama** [comment]
Hi guys,
here's the solution for this (iOS)

in the AudioRecorderAPI.h file add:

`#import <AudioToolbox/AudioService.h>`

and then in the AudioRecorderAPI.m add the following under the [audioSession setActive:YES error:&err];

`
UInt32 audioRouteOverride = kAudioSessionOverrideAudioRoute_Speaker;
AudioSessionSetProperty (kAudioSessionProperty_OverrideAudioRoute, sizeof (audioRouteOverride),&audioRouteOverride);
`
And that's it. Build the project again and it should be working.

**Comment by e-oz** [comment]
thanks, @kerlama

**Comment by emj365** [comment]
Thanks. Pull request is welcome.

**Comment by dominikIncibit** [comment]
@kerlama that solved my issue, thanks a lot!

@emj365  please integrate it in the actual plugin.

**Comment by KevinWang15** [comment]
@kerlama Thanks a lot! solved my problem
should be 

```
#import <AudioToolbox/AudioServices.h>
```

instead of 

```
#import <AudioToolbox/AudioService.h>
```

though

**Comment by eeturiakhil** [comment]
Hi emj365, this is Akhil started my first ionic1 project using angular1 used cordova media capture plugin to record audio file but its not working properly in all mobile devices. Saw your plugin but facing problem in integrating into my project. Could you please provide me step-by-step integration steps and also any example mobile app with this plugin integrated

**Comment by emj365** [comment]
@eeturiakhil I'm glad you like this plugin. This is very normal Cordova, you could read https://github.com/emj365/cordova-plugin-audio-recorder-api/blob/master/README.md#cordova-audio-recorder-api-plugin first. If it can't solve your problem I suggest you read more articles or check questions on StackOverflow about install Cordova plugins.
