### ISSUE TITLE
It not works on device？

### ISSUE THREAD

**Issue by puny-d** [emj365/cordova-plugin-audio-recorder-api#9]
Hi:
I found this plugin works well on ios simulator, but seem not works on device, and every recording file  only 1s？

**Comment by emj365** [comment]
I found the recording timeout(as the method parameter) in iOS has many problems. I will try to use the timer to control the recording just like I did in Android.

**Comment by puny-d** [comment]
Thank you, could I disable the recording timeout without passing any parameter?
谢谢！

**Comment by emj365** [comment]
Good idea. 
Hasn't a parameter to disable that for now.
So far, you can try set the timeout to a huge number. The stop method will works fine. But I am not sure it can fix the issue in that way.
不用客气：）

**Comment by puny-d** [comment]
Have you make any changes to the code?I have found it still fail when I test it on device, and every recording file seems to be 1s, without any sound. But when I test it on ios simulator, it works well.

My device is iphone6 plus, iOS 8.4.

**Comment by emj365** [comment]
As you can see, I haven't committed yet. I'm waiting for my Apple Develop account active mail. So I can't test it on the device for now.
However pull request is welcome ;)

**Comment by emj365** [comment]
https://github.com/emj365/cordova-plugin-audio-recorder-api/blob/master/src/ios/AudioRecorderAPI.m#L57

you can check this.

**Comment by puny-d** [comment]
Thank you very much. I am sorry that I am not familiar with objective-c, But when I test on the device, the log on the terminal seems to works fine.
 So I cloud only wait for your testing, Thanks!

**Comment by emj365** [comment]
@puny-d I tried it in my iPad mini. Doesn't has the problem which you describe. Please check your JS code. 

And I wish I can push an Ionic demo app for this plugin soon.

So far, you can check https://github.com/emj365/test_ionic. It's ugly but works.

**Comment by emj365** [comment]
@puny-d, please try my testing code. Thanks for the feedback. My iPad is iOS 8.4, that works.

**Comment by puny-d** [comment]
Thank you very much, I have reinstall your plugin, It works now
